### ISSUE TITLE
Example request: arguments

### ISSUE THREAD

**Issue by rhn** [geophile/marcel#19]
The pipeline example shows how to use data items passed by the previous part of the pipeline, but doesn't allow specifying arguments:

```
$ l = (|ls|)
$ l foo
Wrong number of arguments for pipeline l = ls
```

This makes creating custom commands limited.

**Comment by geophile** [comment]
Arguments to pipelines need to be declared. Try this:

    l = (| dir: ls (dir) |)
    l foo

dir: declares the argument. "ls dir" won't work, that looks for a directory named "dir". "ls (dir)" causes the value of the dir variable to be returned, which is "foo" in that invocation on the second line.
