### ISSUE TITLE
[Documentation] default configuration path

### ISSUE THREAD

**Issue by vlagorsse** [geophile/marcel#21]
The default configuration file in the doc is said to be under `~/.marcel.py` while `Locations::config_path` returns something like `~/.config/marcel/startup.py`.

**Comment by geophile** [comment]
Yes, the docs are stale. I am working on updating them. The configuration used to be in ~/.marcel.py. It is now located in $XDG_CONFIG_HOME/.config/marcel/startup.py. If XDG_CONFIG_HOME is not set, then it's ~/.config/marcel/startup.py.

**Comment by geophile** [comment]
The website is fixed, and I have checked the code for references to .marcel.py, (there weren't any).
