### ISSUE TITLE
marcel doesn't run ipython

### ISSUE THREAD

**Issue by ZianElijahSmith** [geophile/marcel#26]
![Screenshot from 2023-11-22 11-21-58](https://github.com/geophile/marcel/assets/121137084/ab9faf9f-c2c8-446d-89e1-897a7ed6a572)

Tried out marcel, some of it's features I liked, some issues I think could use some work.

One issue is I could not run iPython in my shell once I invoked marcel.

**Comment by geophile** [comment]
Please let me know what you liked and didn't like. I'd love the detailed feedback, and I'm interested in making marcel work better for more people.

I haven't tried marcel in iPython. Let me try it and I'll get back to you.

**Comment by geophile** [comment]
In marcel, try "bash -i ipython". That seems to at least let ipython get started. I don't work with iPython, so I can't yet talk about how they compare, but my sense is that they do some things in common (being shells), but have different design goals.

**Comment by ZianElijahSmith** [comment]
That works!

bash -i ipython

iPython's goal is to make the lives of programmers like me easier by adding features into the iPython interpreter that are not found in CPython's interpreter. It wasn't intended to be an entire shell like bash or marcel, but it is something I use in the shell a lot and so wanted to try out with marcel.

Thanks for helping! I'll close the issue and I'll keep messing with marcel when I have time.

![Screenshot from 2023-11-23 02-35-39](https://github.com/geophile/marcel/assets/121137084/96c989e8-3f1c-4d73-9b0e-8a7c870d6807)
