### ISSUE TITLE
Missing GitHub releases

### ISSUE THREAD

**Issue by jiripospisil** [geophile/marcel#27]
Hello, I've noticed the last few releases (tags) are missing their corresponding GitHub [releases](https://github.com/geophile/marcel/releases). These are useful because I can then create a custom Watch on the repository and get notified when a new release is available (I [package](https://aur.archlinux.org/packages/marcel) marcel for Arch Linux AUR). No need to create them retroactively, just for the latest one and then moving forward. Thank you!

**Comment by geophile** [comment]
Thank you for letting me know about this! I'll be sure to create GitHub releases more reliably from now on.

**Comment by geophile** [comment]
I created a release for v0.22.2.
