### ISSUE TITLE
git tags are not monotonically increasing

### ISSUE THREAD

**Issue by a-n-n-a-l-e-e** [geophile/marcel#28]
the git tag [v10.0.1](https://github.com/geophile/marcel/releases/tag/v10.0.1) is out of order and causes confusion with nixpkgs auto-updater. eg: https://github.com/NixOS/nixpkgs/pull/288585

can this tag get removed or renamed?
thx

**Comment by geophile** [comment]
I removed it. I don't think anyone is dependent on it, I'm certainly not.
